apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: debug
    image: debug-pod:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
